### PR TITLE
Search interfaces for mapper settings

### LINKED ISSUE #45: Support MapperSettings on parent classes
I have a set of classes that should never have their public methods serialized, so I would like to place a `MapperSettings` on this interface. Right now `DefinitionProvider::resolveObjectSettings` only supports reading the settings from the current class.

However, [ReflectionClass::getAttributes()][1] supports `flags`, so we could do:

```php
$attributes = $reflection->getAttributes(MapperSettings::class, ReflectionAttribute::IS_INSTANCEOF);
```

[1]: https://www.php.net/manual/en/reflectionclass.getattributes.php

### PR DESCRIPTION
**Pull request by shadowhand**
Fixes #45

### CODE REVIEW

**Comment by frankdejonge** [comment]
Can we remove the parent lookup? I'm not sure if that promotes the right stuff. I think the interface based tagging is alright, but tying it to inheritance seems a bit against the spirit of value objects and DTO's.

**Comment by shadowhand** [comment]
That is fine with me, interfaces are effectively at the same "plane" as the DTO. I'll make an adjustment and also update the documentation.

**Comment by frankdejonge** [comment]
Cool 👍 ping me when it's ready and I'll start the release process for this.

**Comment by shadowhand** [comment]
@frankdejonge updated.

**Comment by shadowhand** [comment]
@frankdejonge thanks for the quick response, this really helps clean up a specific area of our code.

**Pull request merged**
